version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite_app
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=database_ignite_app
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app_ignite:
    build: .
    container_name: ignite_app
    # ports: 
    #   - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local